/**
*@author Athene Group LLC
*@date 2017.05
*@group Apex Class - Constants class
*@description Constants class
*/
public class MonetaConstants {
    public static String FSC_ClientGroupId = 'Current Client Group ID';
    public static String HouseholdRecordtype = 'Household';
    public static String InstitutionRecordtype = 'Institution';
    public static String IndividualRecordtype = 'Individual';
    public static String EmailId = 'shailaja.ginka@theathenegroup.com';
    public static String object_FA = 'FinServ__FinancialAccount__c';
    public static String object_Account = 'Account';
    public static String object_Contact = 'Contact';
    public static String object_FH = 'FinServ__FinancialHolding__c';
    public static String object_FAR = 'FinServ__FinancialAccountRole__c';
    public static String farRolePrimaryOwner = 'Primary Owner';
    public static String objectA2CRel = 'AccountContactRelation';
    public static String defaultBDHouseholdName = 'Black Diamond Integration Household';
    public static String defaultBDPrimaryName = 'Black Diamond Integration';
}